name: silverexpress
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  auth0_flutter: ^1.2.1
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_dotenv: ^5.1.0
  flutter_vector_icons: ^2.0.0
  go_router: ^8.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env